defaults:
  - _self_
  - dataset: mazda-v1                 # デフォルトのデータセット
  - model: dot                        # デフォルトのモデル
  - settings: default
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  run:
    dir: ./hydra_experiment/${now:%Y-%m-%d-%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ./hydra_experiment/${settings.mlflow_exp_name}
    subdir: ${now:%Y-%m-%d-%H-%M-%S}
  sweeper:
    sampler:
      seed: ${settings.seed}
    direction: ${dataset.direction}
    study_name: ${settings.mlflow_exp_name}
    storage: null
    n_trials: 100 # Optunaの試行回数
    n_jobs: 1
    params: null
